[package]
name = "google2005"
version = "0.1.0"
edition = "2021"

[dependencies]
askama = "0.11.1"
chunked_transfer = "1.4.0"
ego-tree = "0.6.2"
fastly = "^0.8.2"
serde = "1.0.136"
scraper = "0.12.0"
# tokio = { version = "1.17.0", features = ["full"] }
urlencoding = "2.1.0"